### PR TITLE
Create python

### PR DESCRIPTION
**Pull request by patilcodes**

### CODE REVIEW

**Comment by pratikghule** [comment]
Thanks for contributing to this repository but you have to format your naming semantics.
Example
Repository -> Python -> python-hello_world.py

You have to make the above changes in your PR in order to get it merged.
Thank you!

**Review by patilcodes — COMMENTED** [review]
python-hello_world.py

**Comment by patilcodes** [comment]
Please check

**Comment by patilcodes** [comment]
Thanks

**Pull request merged**
